# Generated by Django 5.1.4 on 2024-12-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_tax_percentage_product_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax',
            new_name='tax_percentage',
        ),
    ]
